# Generated by Django 2.1.4 on 2019-01-10 18:50

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_priority', models.IntegerField()),
                ('alert_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerts',
                'verbose_name_plural': 'Alerts',
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('alert_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('medicaid_eligible', models.CharField(blank=True, max_length=50, null=True)),
                ('ltc', models.CharField(blank=True, max_length=50, null=True)),
                ('spousal', models.CharField(blank=True, max_length=50, null=True)),
                ('application_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_application_submission', models.DateTimeField(blank=True, null=True)),
                ('date_of_application_submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('medicaid_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_nami', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('copay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secondary_pays_copay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_state', models.CharField(blank=True, max_length=50, null=True)),
                ('application_county', models.CharField(blank=True, max_length=50, null=True)),
                ('spousal_refusal', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_response', models.CharField(blank=True, max_length=20, null=True)),
                ('dss_contact_address', models.CharField(blank=True, max_length=100, null=True)),
                ('dss_contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('dss_contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('dss_contact_fax', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=application.models.get_path)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_recieved', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Phases',
                'verbose_name_plural': 'Phases',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resident_number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_id', models.IntegerField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_payor_id', models.IntegerField(blank=True, null=True)),
                ('primary_payor_grp', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_payor', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_payor_id', models.IntegerField(blank=True, null=True)),
                ('secondary_payor_grp', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_payor', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_date', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=2, null=True)),
                ('tracking_status', models.BooleanField(blank=True, null=True)),
                ('dismiss', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Residents',
                'verbose_name_plural': 'Residents',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
            ],
            options={
                'verbose_name': 'Responses',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('response_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Response Types',
                'verbose_name_plural': 'Response Types',
            },
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('rfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('rfi_due_date', models.DateTimeField(blank=True, null=True)),
                ('rfi_extension_request', models.CharField(blank=True, max_length=50, null=True)),
                ('rfi_extension_response', models.CharField(blank=True, max_length=50, null=True)),
                ('rfi_documentation_submitted', models.CharField(blank=True, max_length=50, null=True)),
                ('rfi_documentation_submitted_date', models.DateField(blank=True, null=True)),
                ('rfi_response', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Response')),
            ],
            options={
                'verbose_name': 'RFIS',
                'verbose_name_plural': 'RFIS',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='response_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ResponseType'),
        ),
        migrations.AddField(
            model_name='application',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Phase'),
        ),
        migrations.AddField(
            model_name='application',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Resident'),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.AlertType'),
        ),
        migrations.AddField(
            model_name='alert',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Resident'),
        ),
    ]
