# Generated by Django 2.1.2 on 2018-12-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtracking',
            old_name='medicaid_comfirmation',
            new_name='medicaid_confirmation',
        ),
    ]
