# Generated by Django 2.1.4 on 2019-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denial',
            name='denial_letter_received',
            field=models.CharField(blank=True, default='true', max_length=50, null=True),
        ),
    ]
