# Generated by Django 2.1.4 on 2019-01-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='rfi_documentation_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
