# Generated by Django 2.1.4 on 2019-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tracking_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
