# Generated by Django 2.1 on 2018-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='primary_payor_grp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='secondary_payor_grp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
