# Generated by Django 2.1.4 on 2019-01-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtracking',
            name='initial_response',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rfi',
            name='response',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
