# Generated by Django 2.1 on 2018-11-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181127_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='LTC',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='application_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='application_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='application_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='appointment_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='approval_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='approval_notice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='approval_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='approval_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='copay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_recertification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_rfi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='dss_contact_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='dss_contact_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='dss_contact_fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='dss_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='estimated_nami',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='fair_hearing_notice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='fair_hearing_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='is_medicaid_pending',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_application',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_approval',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_comfirmation',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Alert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='recertification_alert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='rfi',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='rfi_deadline_alert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='secondary_pays_copay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='spousal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='spousal_refusal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
