# Generated by Django 2.1.4 on 2019-01-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='copay_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
