# Generated by Django 2.1.3 on 2018-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181226_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='dismiss',
            field=models.BooleanField(default=False),
        ),
    ]
