# Generated by Django 2.1 on 2018-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181105_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='patient_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
