# Generated by Django 2.1 on 2018-12-11 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181211_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Phase'),
        ),
    ]
