# Generated by Django 2.1.4 on 2019-01-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rfi_rfi_documentation_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rfi_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
