# Generated by Django 2.1.4 on 2019-01-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_document_rfi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtracking',
            name='satisfied_with_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
