# Generated by Django 2.1 on 2018-11-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alert_patient_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='application.Alert')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('is_medicaid_pending', models.BooleanField(blank=True, null=True)),
                ('show_errors', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TrackingData',
                'verbose_name_plural': 'TrackingData',
            },
        ),
    ]
