# Generated by Django 2.1.3 on 2018-12-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_resident_dismiss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_recieved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NAMI',
            fields=[
                ('nami_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('extension_response', models.BooleanField(blank=True, null=True)),
                ('document_submitted', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('rfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('extension_request', models.BooleanField(blank=True, null=True)),
                ('extension_response', models.BooleanField(blank=True, null=True)),
                ('document_submitted', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='date_of_rfi',
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='medicaid_application',
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='medicaid_approval',
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='medicaid_confirmation',
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='notes_file',
        ),
        migrations.RemoveField(
            model_name='applicationtracking',
            name='rfi',
        ),
        migrations.AddField(
            model_name='rfi',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationTracking'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document'),
        ),
        migrations.AddField(
            model_name='rfi',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Resident'),
        ),
        migrations.AddField(
            model_name='nami',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationTracking'),
        ),
        migrations.AddField(
            model_name='nami',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document'),
        ),
        migrations.AddField(
            model_name='nami',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Resident'),
        ),
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationTracking'),
        ),
        migrations.AddField(
            model_name='document',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Resident'),
        ),
    ]
