# Generated by Django 2.1.4 on 2019-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190402_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
