# Generated by Django 2.1.2 on 2019-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_document_rfi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtracking',
            name='date_of_medicaid_submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
