# Generated by Django 2.1.4 on 2019-01-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_copay_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_recieved',
            new_name='date_uploaded',
        ),
    ]
