# Generated by Django 2.1 on 2018-10-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='fname',
            new_name='fisrt_name',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='ssn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='tracking_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
