# Generated by Django 2.1.3 on 2018-12-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20181127_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackingData',
            new_name='ApplicationTracking',
        ),
        migrations.RenameModel(
            old_name='Alert',
            new_name='Patient',
        ),
        migrations.AlterModelOptions(
            name='applicationtracking',
            options={'verbose_name': 'ApplicationTracking', 'verbose_name_plural': 'ApplicationTracking'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patients', 'verbose_name_plural': 'Patients'},
        ),
    ]
