# Generated by Django 2.1.3 on 2018-12-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20181204_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name_num',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name_num',
        ),
    ]
