# Generated by Django 2.1.4 on 2019-04-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190403_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSSLogEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('entry_contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_notes', models.CharField(blank=True, max_length=5000, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'verbose_name': 'DSS Log Entry',
                'verbose_name_plural': 'DSS Log Entries',
            },
        ),
    ]
