# Generated by Django 2.1.4 on 2019-01-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationtracking_satisfied_with_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtracking',
            name='fair_hearing_required',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='satisfied_with_approval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
