# Generated by Django 2.1 on 2018-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_trackingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='application_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_recertification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_medicaid_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='date_of_rfi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_application',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_approval',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_comfirmation',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='medicaid_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='rfi',
            field=models.FileField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
