# Generated by Django 2.1.4 on 2019-04-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190403_1442'),
        ('application', '0002_auto_20190313_1305'),
    ]

    operations = [
    ]
