# Generated by Django 2.1.3 on 2019-01-01 20:32

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20181227_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=application.models.get_path),
        ),
    ]
