# Generated by Django 2.1 on 2018-10-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20181026_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
