# Generated by Django 2.1.4 on 2019-05-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_merge_20190404_1444'),
        ('application', '0005_dsslogentry'),
    ]

    operations = [
    ]
