# Generated by Django 2.1.3 on 2018-12-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20181204_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_priority', models.IntegerField()),
                ('alert_status', models.BooleanField(default=False)),
                ('alertt_message', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationTracking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Patient')),
            ],
        ),
    ]
