# Generated by Django 2.1.3 on 2019-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190101_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
