# Generated by Django 2.1 on 2018-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20181106_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingdata',
            name='is_medicaid_pending',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
