# Generated by Django 2.1.4 on 2019-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20190109_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi',
            name='rfi_documentation_submitted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='rfi_extension_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='rfi_extension_response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
