# Generated by Django 2.1 on 2018-10-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='facility',
        ),
    ]
