# Generated by Django 2.1.3 on 2018-12-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alertt_message',
            new_name='alert_message',
        ),
    ]
