# Generated by Django 2.1 on 2018-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20181107_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
