# Generated by Django 2.1 on 2018-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alert_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='first_name_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_name_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
