# Generated by Django 2.1.2 on 2018-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_alert_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='fisrt_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='facility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='facility_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='primary_payor_grp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='primary_payor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='secondary_payor_grp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='secondary_payor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
