# Generated by Django 2.1.3 on 2018-12-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20181204_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ApplicationTracking'),
        ),
    ]
