# Generated by Django 2.1.3 on 2018-12-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20181204_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Resident',
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Residents', 'verbose_name_plural': 'Residents'},
        ),
    ]
