# Generated by Django 2.1.2 on 2018-11-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20181031_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='primary_payor_grp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='secondary_payor_grp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
