# Generated by Django 2.1.4 on 2019-01-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190111_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_notice_date', models.DateTimeField(blank=True, null=True)),
                ('satisfied_with_approval', models.CharField(blank=True, max_length=50, null=True)),
                ('fair_hearing_required', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Response')),
            ],
            options={
                'verbose_name': 'Approvals',
                'verbose_name_plural': 'Aprrovals',
            },
        ),
        migrations.CreateModel(
            name='NAMI',
            fields=[
                ('nami_id', models.AutoField(primary_key=True, serialize=False)),
                ('nami_start_date', models.DateField(blank=True, null=True)),
                ('nami_end_date', models.DateField(blank=True, null=True)),
                ('nami_amount', models.FloatField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Approval')),
            ],
            options={
                'verbose_name': 'NAMIS',
                'verbose_name_plural': 'NAMIS',
            },
        ),
    ]
