# Generated by Django 2.1.2 on 2019-01-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_approval_nami'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('confirmation_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_uploaded', models.DateTimeField(blank=True, null=True)),
                ('confirmation_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
            ],
            options={
                'verbose_name': 'Confirmations',
                'verbose_name_plural': 'Confirmations',
            },
        ),
        migrations.CreateModel(
            name='Denial',
            fields=[
                ('denial_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Response')),
            ],
            options={
                'verbose_name': 'Denials',
                'verbose_name_plural': 'Denials',
            },
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Approvals', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AddField(
            model_name='application',
            name='application_confirmation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Confirmation'),
        ),
    ]
