# Generated by Django 2.1.2 on 2019-01-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_approval_nami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Approvals', 'verbose_name_plural': 'Approvals'},
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_recertification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
       
    ]
