# Generated by Django 2.1.4 on 2019-01-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20190115_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denial',
            fields=[
                ('denial_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Response')),
            ],
            options={
                'verbose_name': 'Denials',
                'verbose_name_plural': 'Denials',
            },
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'verbose_name': 'Approvals', 'verbose_name_plural': 'Approvals'},
        ),
    ]
