# Generated by Django 2.1.4 on 2019-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190121_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approval_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approval_recertification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='approval_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
