# Generated by Django 2.1.4 on 2019-01-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190121_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairHearing',
            fields=[
                ('fair_hearing_id', models.AutoField(primary_key=True, serialize=False)),
                ('fair_hearing_date', models.DateField(blank=True, null=True)),
                ('fair_hearing_time', models.TimeField(blank=True, null=True)),
                ('fair_hearing_address', models.CharField(blank=True, max_length=50, null=True)),
                ('fair_hearing_outcome', models.CharField(blank=True, max_length=50, null=True)),
                ('fair_hearing_appeal', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='dismiss',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
