# Generated by Django 2.1.4 on 2019-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20190121_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approval_end_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='approval_recertification_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='approval_start_date',
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_recertification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
