# Generated by Django 2.1.4 on 2019-01-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20190123_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='dismiss',
            field=models.BooleanField(default=False),
        ),
    ]
