# Generated by Django 2.1.4 on 2019-01-24 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0013_auto_20190123_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('Stubin Center', 'Can View Stubin Center Residents'),),
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_pcc_id', models.IntegerField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Facilities',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_attorney_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_attorney_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_coordinator_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_coordinator_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_outcome_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Document'),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_regional_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_regional_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_satisfied',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fairhearing',
            name='fair_hearing_appeal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
