# Generated by Django 2.1.4 on 2019-01-24 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20190124_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snowden',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('column_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=250)),
                ('new_value', models.CharField(max_length=250)),
                ('log_ip', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'verbose_name': 'Edward Snowden',
                'verbose_name_plural': 'Edward Snowden',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('Beth Abraham', 'Can View Beth Abraham Center Residents'), ('Boro Park', 'Can View Boro Park Center Residents'), ('Steuben', 'Can View Steuben Center Residents')), 'verbose_name': 'Employees', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='fairhearing',
            options={'verbose_name': 'Fair Hearings', 'verbose_name_plural': 'Fair Hearings'},
        ),
        migrations.AddField(
            model_name='snowden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Employee'),
        ),
    ]
