# Generated by Django 2.1.5 on 2019-01-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20190124_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowden',
            name='application',
        ),
        migrations.AddField(
            model_name='snowden',
            name='row_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
