# Generated by Django 2.1.5 on 2019-01-28 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20190128_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
