# Generated by Django 2.1.5 on 2019-01-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20190128_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fairhearing',
            name='application',
        ),
        migrations.AddField(
            model_name='denial',
            name='denial_documentation_submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denial',
            name='denial_fair_hearing_request',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='denial',
            name='denial_notice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Response'),
        ),
        migrations.AlterField(
            model_name='snowden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Employee'),
        ),
    ]
