# Generated by Django 2.1.5 on 2019-01-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20190129_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowden',
            name='application',
        ),
        migrations.AddField(
            model_name='snowden',
            name='row_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
