# Generated by Django 2.1.4 on 2019-01-30 17:13

from django.db import migrations
import pgcrypto_expressions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20190130_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='ssn',
            field=pgcrypto_expressions.fields.EncryptedCharField(blank=True, max_length=50, null=True),
        ),
    ]
