# Generated by Django 2.1.4 on 2019-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20190130_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fairhearing',
            old_name='fair_hearing_attorney_first_name',
            new_name='fair_hearing_representative_type',
        ),
        migrations.RemoveField(
            model_name='fairhearing',
            name='fair_hearing_attorney_last_name',
        ),
        migrations.RemoveField(
            model_name='fairhearing',
            name='fair_hearing_coordinator_first_name',
        ),
        migrations.RemoveField(
            model_name='fairhearing',
            name='fair_hearing_coordinator_last_name',
        ),
        migrations.RemoveField(
            model_name='fairhearing',
            name='fair_hearing_regional_first_name',
        ),
        migrations.RemoveField(
            model_name='fairhearing',
            name='fair_hearing_regional_last_name',
        ),
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_representative_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
