# Generated by Django 2.1.4 on 2019-01-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20190131_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairhearing',
            name='fair_hearing_confirmation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Confirmation'),
        ),
    ]
