# Generated by Django 2.1.4 on 2019-02-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_fairhearing_fair_hearing_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='application',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resident',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
