# Generated by Django 2.1.4 on 2019-02-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20190204_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_priority', models.IntegerField()),
                ('alert_status', models.BooleanField(default=False)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.AlertType')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Resident')),
            ],
            options={
                'verbose_name': 'Alerts',
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
