# Generated by Django 2.1.4 on 2019-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_priority',
        ),
        migrations.AddField(
            model_name='alerttype',
            name='alert_priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
