# Generated by Django 2.1.4 on 2019-02-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20190204_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttype',
            name='alert_class',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
