# Generated by Django 2.1.4 on 2019-02-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_application_approval_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denial',
            old_name='denial_document',
            new_name='document',
        ),
    ]
