# Generated by Django 2.1.4 on 2019-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20190221_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('Boro Park', 'Boro Park'), ('Brooklyn', 'Brooklyn'), ('Bushwick', 'Bushwick'), ('Washington', 'Washington'), ('Corning', 'Corning'), ('Argyle Center', 'Argyle Center'), ('Bronx', 'Bronx'), ('Warren', 'Warren'), ('Deptford', 'Deptford'), ('Oak Hill', 'Oak Hill'), ('Beth Abraham', 'Beth Abraham'), ('Essex', 'Essex'), ('Far Rockaway', 'Far Rockaway'), ('Fulton', 'Fulton'), ('Carthage', 'Carthage'), ('Hammonton', 'Hammonton'), ('Holliswood', 'Holliswood'), ('Hope Center', 'Hope Center'), ('WC - Elm Manor', 'WC - Elm Manor'), ('Mount Laurel', 'Mount Laurel'), ('N. Manor', 'Northern Manor'), ('Ellicott', 'Ellicott Center'), ('N. Metropolitan', 'N. Metropolitan'), ('Glens Falls', 'Glens Falls'), ('N. Riverview', 'N. Riverview'), ('New Paltz', 'New Paltz'), ('Ontario Center', 'Ontario Center'), ('Ontario County', 'Ontario County'), ('STBN County', 'STBN County'), ('Onondaga', 'Onondaga'), ('PG - Quality Care', 'Quality Care'), ('PG - Stamford Residence', 'Stamford Residence'), ('PG - Walnut Hills', 'Walnut Hills'), ('PG - Westview Manor', 'Westview Manor'), ('Claremont ALP', 'Claremont'), ('Steuben', 'Steuben'), ('Suffolk', 'Suffolk'), ('University', 'University'), ('Williamsbridge', 'Williamsbridge'), ('Bannister', 'Bannister'), ('Buffalo', 'Buffalo'), ('Park View', 'Park View'), ('Schenectady', 'Schenectady'), ('Slate Valley', 'Slate Valley'), ('Triboro (ALP)', 'Alpine Triboro Center'), ('Triboro Center', 'Triboro Center'), ('Troy', 'Troy'), ('Centers for Care', 'Centers for Care'), ('Brookside - MA', 'Brookside'), ('Granville', 'Granville'), ('Evolve', 'Evolve'), ('Kingston', 'Kingston'), ('New Boston', 'New Boston'), ('WC - Wedgewood', 'Wedgewood'), ('Cooperstown', 'Cooperstown'), ('Martine', 'Martine'), ('Focus - Otsego - Charts', 'Otsego'), ('Focus - Utica - Charts', 'Utica'), ('EC - Midwest', 'Midwest'), ('EC - Southwest', 'Southwest Center'), ('Mills Pond', 'Mills Pond'), ('Sayville', 'Sayville'), ('Birchwood - VT', 'Birchwood'), ('WC - Folts ADC', 'Folts ADC'), ('EC - Tulsa', 'Tulsa'), ('EC - Claremore', 'Claremore'), ('EC - Memory Care', 'Memory Care'), ('Castle Senior Living', 'Castle Senior Living'), ('Focus Senior Living', 'Focus Senior Living'), ('Richmond (Staten Island)', 'Richmond Center'), ('WC - Folts Home', 'Folts Home'), ('Creekview', 'Creekview'), ('EC - Crystal', 'Crystal Center'), ('EC - Pikeville', 'Pikeville'), ('Kansas City ALF', 'Kansas City ALF'), ('Overland Park ALF', 'Overland Park ALF'), ('Oneida Center', 'Oneida Center'), ('Butler Center', 'Butler Center'), ('Kansas City', 'Kansas City'), ('Overland Park', 'Overland Park'), ('Ten Broeck', 'Ten Broeck'), ('Topeka Center', 'Topeka Center'), ('Wichita Center', 'Wichita Center')), 'verbose_name': 'Employees', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
