# Generated by Django 2.1.4 on 2019-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20190226_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
