# Generated by Django 2.1.4 on 2019-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20190312_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='medicaid_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
